### ISSUE TITLE
通常include下会放很多server的配置，如何方便解析和修改数据

### ISSUE THREAD

**Issue by safejob** [ClessLi/go-nginx-conf-parser#2]
大佬，你的这个解析方式很巧妙，非常适合处理nginx配置，最近正在研究
在学习的过程中，发现一个问题，通常include下会放很多server的配置，如何方便解析和修改数据呢，由于 Children是个接口类型，要解析下层只能类型断言，这现一层层断言层次比较深，有什么好办法不

`
	config, _ := resolv.Load("../test/nginx.conf")

	for _, k := range config.Children {
		switch k.(type) {
		//case *resolv.Events:
		//k.(*resolv.Events).Add(&resolv.Key{Name: "xx", Value: "yy"})
		case *resolv.Http:
			for _, p := range k.(*resolv.Http).Children {
				switch p.(type) {
				case *resolv.Include:
					for _, q := range p.(*resolv.Include).Children {
						switch q.(type) {
						case *resolv.Config:
							fmt.Println(q.(*resolv.Config).Name, q.(*resolv.Config).Value)
						}
					}
				}
			}
		}
	}
`

`
server_name ~^xxx[1-4]\.xxxxx\.com$
`
另外，如果server_name中使用正则，如上面这样，json.Marshal(conf) 会报错：
json: error calling MarshalJSON for type *resolv.Key: invalid character '.' in string escape code
看能解决不

**Comment by ClessLi** [comment]
感谢你提供的代码。目前已调整了上下文对象(BasicContext)的Servers()（以及Server()）方法：
func (c *BasicContext) Servers() []Parser {
	svrs := make([]Parser, 0)
	for _, child := range c.Children {

		switch child.(type) {
		case Context:
			switch child.(type) {
			case *Server:
				svrs = append(svrs, child)
			default:
				svrs = append(svrs, child.(Context).Servers()...)
			}
		}

	}
	return svrs
}
并且Include对象也是基于上下文对象，因此继承了 Servers() 和 Server() 方法。
